# Generated by Django 5.0.4 on 2024-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='quota_type',
            field=models.CharField(max_length=50),
        ),
    ]
