# Generated by Django 5.0.4 on 2024-04-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0002_alter_quota_quota_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='quota_type',
            new_name='quota',
        ),
    ]
