# Generated by Django 5.0.4 on 2024-04-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0003_rename_quota_type_quota_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('group', models.CharField(max_length=50)),
                ('fee', models.IntegerField(null=True)),
                ('pta_fund', models.IntegerField(null=True)),
                ('others', models.IntegerField(null=True)),
                ('library', models.IntegerField(null=True)),
                ('uniform_boys', models.IntegerField(null=True)),
                ('uniform_girls', models.IntegerField(null=True)),
            ],
        ),
    ]
