# Generated by Django 5.0.4 on 2024-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0004_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='fee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='library',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='others',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='pta_fund',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='uniform_boys',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='uniform_girls',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
