# Generated by Django 5.0.4 on 2024-04-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0005_alter_group_fee_alter_group_library_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district_name',
            new_name='name',
        ),
    ]
