# Generated by Django 5.0.4 on 2024-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0008_diocese_parish'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='name',
            field=models.CharField(default='...', max_length=100),
        ),
    ]
