# Generated by Django 5.0.4 on 2024-04-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0009_parish_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
