# Generated by Django 5.0.4 on 2024-04-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0011_constants_remove_group_library_remove_group_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='stream',
            field=models.CharField(default='Science', max_length=50),
        ),
    ]
