# Generated by Django 5.0.4 on 2024-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0017_rename_birthdate_student_addate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AdNum',
            field=models.IntegerField(unique=True),
        ),
    ]
