# Generated by Django 5.0.4 on 2024-04-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0018_alter_student_adnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PrevSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_school', to='hssm.school'),
        ),
    ]
