# Generated by Django 5.0.4 on 2024-04-24 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0020_class_student_adclassnow_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='religion',
        ),
        migrations.AddField(
            model_name='class',
            name='home_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_teachers', to='hssm.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='HSEMonthYear',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='HSERegNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='TCDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='TCNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='TCYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dateOfLeaving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fullAPlus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='passedHSE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='reasonForLeaving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reason_for_leaving', to='hssm.status'),
        ),
    ]
