# Generated by Django 5.0.4 on 2024-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0021_remove_teacher_designation_remove_teacher_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='FeeDue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
