# Generated by Django 5.0.4 on 2024-04-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0022_student_feedue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cgpa',
            new_name='CGPA',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='HSEMonthYear',
            new_name='HSEMonYear',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='HSERegNo',
            new_name='HSEReg',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='reasonForLeaving',
            new_name='LeaveReason',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='dateOfLeaving',
            new_name='LeavingDate',
        ),
    ]
