# Generated by Django 5.0.4 on 2024-04-25 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0023_rename_cgpa_student_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StudyStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_status', to='hssm.status'),
        ),
    ]
