# Generated by Django 5.0.4 on 2024-05-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0026_alter_student_gname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='IED',
            field=models.CharField(default='off', max_length=3, null=True),
        ),
    ]
