# Generated by Django 5.0.4 on 2024-05-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0028_alter_student_ied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='IED',
            field=models.BooleanField(choices=[('true', 1), ('false', 0)], default='false', null=True),
        ),
    ]
