# Generated by Django 5.0.4 on 2024-05-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0030_alter_student_ied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='IED',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
