# Generated by Django 5.0.4 on 2024-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0032_alter_student_hsemonyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fullAPlus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passedHSE',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
