# Generated by Django 5.0.4 on 2024-05-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0033_alter_student_fullaplus_alter_student_passedhse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PrevSchool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_school', to='hssm.school'),
        ),
    ]
