# Generated by Django 5.0.4 on 2024-05-23 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0034_alter_student_prevschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='FOccupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_occupation', to='hssm.occupation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='MOccupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_occupation', to='hssm.occupation'),
        ),
    ]
