# Generated by Django 5.0.4 on 2024-05-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0035_alter_student_foccupation_alter_student_moccupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='FeePaid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
