# Generated by Django 5.0.4 on 2024-05-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0037_remove_student_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar',
            field=models.BigIntegerField(blank=True, default=999999999999, null=True),
        ),
    ]
