# Generated by Django 5.0.4 on 2024-05-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0038_alter_student_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bankBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_branch', to='hssm.bank'),
        ),
    ]
