# Generated by Django 5.0.4 on 2024-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0039_alter_student_bankbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
