# Generated by Django 5.0.4 on 2024-05-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0041_alter_student_adbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
