# Generated by Django 5.0.4 on 2024-05-25 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0043_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hssm.client'),
        ),
        migrations.AddField(
            model_name='constant',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hssm.client'),
        ),
        migrations.AddField(
            model_name='group',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hssm.client'),
        ),
        migrations.AddField(
            model_name='student',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hssm.client'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hssm.client'),
        ),
    ]
