# Generated by Django 5.0.4 on 2024-05-26 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0046_alter_student_adnum_student_unique_adnum_per_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='hssm.school'),
        ),
    ]
