# Generated by Django 5.0.4 on 2024-05-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0047_alter_client_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='code',
        ),
    ]
