# Generated by Django 5.1.1 on 2024-10-03 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hssm', '0050_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('max_marks', models.IntegerField()),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hssm.client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hssm.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hssm.subject')),
            ],
        ),
    ]
