# Generated by Django 6.0.5 on 2026-05-10 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuition_concession', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pta_fund', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('library_fee', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('other_fees', models.DecimalField(decimal_places=2, default=800, max_digits=10)),
                ('uniform_boys', models.DecimalField(decimal_places=2, default=1300, max_digits=10)),
                ('uniform_girls', models.DecimalField(decimal_places=2, default=1800, max_digits=10)),
                ('academic_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure', to='academics.academicgroup')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_cleared', models.BooleanField(default=False)),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
