# Generated by Django 6.0.5 on 2026-05-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_num', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('ad_date', models.DateField()),
                ('ad_year', models.CharField(max_length=9)),
                ('ad_class', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admissions', to='academics.schoolclass')),
                ('ad_quota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.quota')),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.caste')),
                ('class_now', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='current_students', to='academics.schoolclass')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.gender')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parish')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.religion')),
                ('study_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.status')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('bank_ac_number', models.CharField(blank=True, max_length=30, null=True)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('pmt_address', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='students.student')),
            ],
        ),
    ]
