# Generated by Django 6.0.5 on 2026-05-12 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_busroute_district_studytype_bank_legacy_code_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='pmt_address',
        ),
        migrations.AddField(
            model_name='student',
            name='app_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_roll_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_catholic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='second_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.secondlanguage'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bus_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.busroute'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathers', to='core.occupation'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothers', to='core.occupation'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pmt_address_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pmt_address_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pmt_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmt_residents', to='core.district'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pmt_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pmt_pin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pst_address_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pst_address_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pst_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pst_residents', to='core.district'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pst_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pst_pin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='StudentAcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_school', models.CharField(blank=True, max_length=250)),
                ('sec_reg_num', models.CharField(blank=True, max_length=50)),
                ('index_score', models.FloatField(blank=True, null=True)),
                ('tc_date', models.DateField(blank=True, null=True)),
                ('tc_number', models.CharField(blank=True, max_length=50)),
                ('reason_for_leave', models.CharField(blank=True, max_length=250)),
                ('passed_hse', models.BooleanField(default=False)),
                ('hse_reg_no', models.CharField(blank=True, max_length=50)),
                ('sec_study_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studytype')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_record', to='students.student')),
            ],
        ),
    ]
