# Generated by Django 6.0.5 on 2026-05-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_school_tenant_code'),
        ('students', '0004_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ad_num',
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.secondlanguage'),
        ),
    ]
