# Generated by Django 6.0.5 on 2026-06-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicgroup_deleted_at_academicgroup_is_deleted_and_more'),
        ('core', '0004_alter_school_tenant_code'),
        ('students', '0005_alter_student_ad_num_alter_student_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HscapCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('allotment_round', models.CharField(default='First Allotment', max_length=150)),
                ('app_num', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('reg_num', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender_text', models.CharField(blank=True, max_length=20)),
                ('second_language_text', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Arrival'), ('TEMP_ADMIT', 'Temporary Admission (Awaiting Higher Option)'), ('LEFT', 'Left for Higher Option')], default='PENDING', max_length=20)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_candidates', to='academics.schoolclass')),
            ],
            options={
                'unique_together': {('school', 'app_num')},
            },
        ),
    ]
