# Generated by Django 6.0.5 on 2026-06-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_hscapcandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='app_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
