# Generated by Django 6.0.5 on 2026-06-07 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classteacherassignment_deleted_at_and_more'),
        ('students', '0007_alter_student_app_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ad_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='admissions', to='academics.schoolclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_now',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='current_students', to='academics.schoolclass'),
        ),
    ]
