# Generated by Django 6.0.5 on 2026-06-07 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_ad_class_alter_student_class_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('scanned_file', models.FileField(blank=True, null=True, upload_to='temp_scans/')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.hscapcandidate')),
            ],
        ),
    ]
