# Generated by Django 6.0.5 on 2026-05-12 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_busroute_district_studytype_bank_legacy_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tenant_code', models.CharField(help_text="e.g., 'kaliyar'", max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
