# Generated by Django 6.0.5 on 2026-05-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='tenant_code',
            field=models.CharField(help_text="e.g., '06018'", max_length=50, unique=True),
        ),
    ]
