# Generated by Django 6.0.5 on 2026-05-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('is_teaching_staff', models.BooleanField(default=True)),
                ('ui_priority', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['ui_priority'],
            },
        ),
        migrations.CreateModel(
            name='ScaleOfPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_range', models.CharField(max_length=50, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Scales of Pay',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('ret_date', models.DateField(blank=True, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('pan_no', models.CharField(blank=True, max_length=20)),
                ('pen_no', models.CharField(blank=True, max_length=20)),
                ('election_id_no', models.CharField(blank=True, max_length=30)),
                ('name_of_lac', models.CharField(blank=True, max_length=100)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pf_account_no', models.CharField(blank=True, max_length=50)),
                ('bank_ac_no', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank')),
                ('caste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.caste')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='staff.designation')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.gender')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parish')),
                ('primary_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.religion')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.status')),
                ('scale_of_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.scaleofpay')),
            ],
            options={
                'ordering': ['designation__ui_priority', 'name'],
            },
        ),
    ]
