# Generated by Django 6.0.5 on 2026-05-24 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicgroup_deleted_at_academicgroup_is_deleted_and_more'),
        ('core', '0004_alter_school_tenant_code'),
        ('staff', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_ac_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='election_id_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name_of_lac',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pen_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pf_account_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='primary_subject',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ret_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='scale_of_pay',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='transfer_date',
        ),
        migrations.CreateModel(
            name='EmployeeDemographicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('caste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.caste')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_record', to='staff.employee')),
                ('religion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.religion')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_no', models.CharField(blank=True, max_length=20)),
                ('pen_no', models.CharField(blank=True, max_length=20)),
                ('pf_account_no', models.CharField(blank=True, max_length=50)),
                ('bank_ac_no', models.CharField(blank=True, max_length=50)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_record', to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(blank=True, null=True)),
                ('ret_date', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_record', to='staff.employee')),
                ('primary_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
            ],
        ),
    ]
