# Generated by Django 6.0.5 on 2026-05-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff', '0005_alter_employee_options_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['designation__ui_priority', 'name']},
        ),
        migrations.AddField(
            model_name='designation',
            name='system_group',
            field=models.ForeignKey(blank=True, help_text='The security permission group automatically mapped to this employment title.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_designations', to='auth.group'),
        ),
    ]
