import os
import sys
import django

sys.path.append(os.getcwd())
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from faker import Faker
from students.models import Student, StudentProfile, StudentAcademicRecord
from core.models import Gender, Religion, Caste, Status, Quota, School, SecondLanguage
from academics.models import SchoolClass

fake = Faker("en_IN")


def seed_students():
    print("Initializing dynamic student database seeding pass...")

    school = School.objects.first()
    gender = Gender.objects.first()
    religion = Religion.objects.first()
    caste = Caste.objects.first()
    status = Status.objects.first()
    quota = Quota.objects.first()
    target_class = SchoolClass.objects.first()
    second_lang = SecondLanguage.objects.first()

    if not all([school, gender, religion, caste, status, quota, target_class]):
        print("Error: Missing lookups or classes. Seed structural setup lookups first.")
        return

    # Seed 15 Fake Higher Secondary Students
    for i in range(15):
        student_name = fake.name()

        # Core admission record allocation
        student = Student.objects.create(
            app_num=(
                random.randint(50000, 99999) if "random" in globals() else 54321 + i
            ),
            name=student_name,
            dob=fake.date_of_birth(minimum_age=16, maximum_age=18),
            gender=gender,
            religion=religion,
            caste=caste,
            ad_date=fake.date_this_year(),
            ad_year="2026-27",
            ad_quota=quota,
            ad_class=target_class,
            class_now=target_class,
            class_roll_num=i + 1,
            second_language=second_lang,
            study_status=status,
            school=school,
        )

        # Update the profile sidecar generated by the automated system signal
        StudentProfile.objects.filter(student=student).update(
            aadhar_number=fake.numerify(text="############"),
            father_name=fake.name_male(),
            mother_name=fake.name_female(),
            pmt_phone=fake.phone_number(),
            pmt_address_1=fake.building_number(),
            pmt_address_2=fake.street_name(),
        )

        # Update the academic record sidecar details
        StudentAcademicRecord.objects.filter(student=student).update(
            prev_school=f"{fake.city()} High School",
            index_score=(
                round(
                    fake.pyfloat(
                        left_digits=3, right_digits=2, min_value=300, max_value=600
                    ),
                    2,
                )
                if "fake" in globals()
                else 450.5
            ),
        )

        print(
            f"Created Student: {student.name} | Admission Number: {student.ad_num} | Roll: {student.class_roll_num}"
        )

    print("Student database seeding complete.")


if __name__ == "__main__":
    import random

    seed_students()
