# Generated by Django 6.0.5 on 2026-05-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InclusionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ied', models.BooleanField(default=False)),
                ('ied_remarks', models.CharField(blank=True, max_length=255)),
                ('ad_quota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.quota')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_data', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_num', models.IntegerField(blank=True, null=True)),
                ('tc_year', models.CharField(blank=True, max_length=9, null=True)),
                ('tc_date', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('reason_for_leave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tc_record', to='students.student')),
            ],
            options={
                'unique_together': {('tc_num', 'tc_year')},
            },
        ),
    ]
