# Generated by Django 6.0.5 on 2026-05-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='academic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classes', to='academics.academicgroup'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_classes', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='core_subjects',
            field=models.ManyToManyField(related_name='groups', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='classteacherassignment',
            unique_together={('school_class', 'subject', 'teacher')},
        ),
    ]
