# Generated by Django 6.0.5 on 2026-06-07 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicgroup_deleted_at_academicgroup_is_deleted_and_more'),
        ('core', '0004_alter_school_tenant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacherassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
